package models

import (
	"time"

	"github.com/google/uuid"
)

// Message represents a message in the system
type Message struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	SenderID       uuid.UUID  `db:"sender_id" json:"sender_id"`
	ReceiverID     *uuid.UUID `db:"receiver_id" json:"receiver_id"`
	GroupID        *uuid.UUID `db:"group_id" json:"group_id"`
	ContentEncrypted []byte   `db:"content_encrypted" json:"-"`
	ContentIV      []byte    `db:"content_iv" json:"-"`
	ContentTag     []byte    `db:"content_tag" json:"-"`
	MessageType    string    `db:"message_type" json:"message_type"` // text, file, image, video, voice, system
	FileID         *uuid.UUID `db:"file_id" json:"file_id"`
	IsEdited       bool      `db:"is_edited" json:"is_edited"`
	EditedAt       *time.Time `db:"edited_at" json:"edited_at"`
	IsDeleted      bool      `db:"is_deleted" json:"is_deleted"`
	DeletedAt      *time.Time `db:"deleted_at" json:"deleted_at"`
	ReadAt         *time.Time `db:"read_at" json:"read_at"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	KeyVersion     int        `db:"key_version" json:"-"`
	ParentID       *uuid.UUID `db:"parent_id" json:"parent_id"`
}

// Conversation represents a 1-to-1 conversation
type Conversation struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID1   uuid.UUID `db:"user_id_1" json:"user_id_1"`
	UserID2   uuid.UUID `db:"user_id_2" json:"user_id_2"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// MessageAttachment represents a file attached to a message
type MessageAttachment struct {
	ID        uuid.UUID `db:"id" json:"id"`
	MessageID uuid.UUID `db:"message_id" json:"message_id"`
	FileID    uuid.UUID `db:"file_id" json:"file_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// SendMessageRequest represents a send message request
type SendMessageRequest struct {
	ReceiverID      *uuid.UUID `json:"receiver_id"`
	GroupID         *uuid.UUID `json:"group_id"`
	Content         string     `json:"content" binding:"max=10000"` // required unless file_id is set (then it is the attachment note)
	// "system" messages (call records) are created by the server only.
	MessageType     string     `json:"message_type" binding:"required,oneof=text file image video voice"`
	FileID          *uuid.UUID `json:"file_id"`
	EncryptionKeyVer int        `json:"encryption_key_version"`
	ParentID         *uuid.UUID `json:"parent_id"` // reply in the thread of this group message
	// ClientID is generated by the client once per composed message and reused on retries, so a
	// retried send returns the original message instead of creating a duplicate.
	ClientID *uuid.UUID `json:"client_id"`
}

// MarkReadRequest acknowledges messages up to and including UpTo (the newest one displayed).
type MarkReadRequest struct {
	UpTo uuid.UUID `json:"up_to" binding:"required"`
}

// GetMessagesRequest represents a get messages request
type GetMessagesRequest struct {
	ConversationID *uuid.UUID `form:"conversation_id"`
	GroupID        *uuid.UUID `form:"group_id"`
	Limit          int        `form:"limit" binding:"omitempty,max=100"`
	Offset         int        `form:"offset" binding:"omitempty,min=0"`
	SinceID        *uuid.UUID `form:"since_id"`
	UntilID        *uuid.UUID `form:"until_id"`
}

// MessageDTO is a data transfer object for message
type MessageDTO struct {
	ID          uuid.UUID     `json:"id"`
	SenderID    uuid.UUID     `json:"sender_id"`
	ReceiverID  *uuid.UUID    `json:"receiver_id"`
	GroupID     *uuid.UUID    `json:"group_id"`
	Content     string        `json:"content"`
	MessageType string        `json:"message_type"`
	FileID      *uuid.UUID    `json:"file_id"`
	IsEdited    bool          `json:"is_edited"`
	EditedAt    *time.Time    `json:"edited_at"`
	ReadAt      *time.Time    `json:"read_at"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	Sender      *UserDTO      `json:"sender,omitempty"`
	Attachments []FileDTO     `json:"attachments,omitempty"`
	// ReadCount is how many recipients have read the message; RecipientCount is how many
	// recipients it had (1 for direct messages, group members at send time for groups).
	ReadCount      int `json:"read_count"`
	RecipientCount int `json:"recipient_count"`

	ParentID         *uuid.UUID    `json:"parent_id,omitempty"`
	ReplyCount       int           `json:"reply_count,omitempty"`
	UnreadReplyCount int           `json:"unread_reply_count,omitempty"`
	LastReplyAt      *time.Time    `json:"last_reply_at,omitempty"`
	Unread           bool          `json:"unread,omitempty"` // not yet read by the viewer
	Mentions         []MentionDTO  `json:"mentions,omitempty"`
}

// MentionDTO is a user @mentioned in a message.
type MentionDTO struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
}

// EditMessageRequest represents an edit message request
type EditMessageRequest struct {
	Content string `json:"content" binding:"max=10000"`
}

// DeleteMessageRequest represents a delete message request
type DeleteMessageRequest struct {
	Reason string `json:"reason"`
}

// MessageListResponse represents a list of messages
type MessageListResponse struct {
	Messages []MessageDTO `json:"messages"`
	Total    int          `json:"total"`
	Limit    int          `json:"limit"`
	Offset   int          `json:"offset"`
}

// ConversationDTO represents a conversation data transfer object
type ConversationDTO struct {
	ID                uuid.UUID  `json:"id"`
	OtherUser         *UserDTO   `json:"other_user"`
	LastMessage       *MessageDTO `json:"last_message"`
	UnreadCount       int        `json:"unread_count"`
	MentionCount      int        `json:"mention_count"`
	CreatedAt         time.Time  `json:"created_at"`
}

// MessageSearchRequest represents a message search request
type MessageSearchRequest struct {
	Query    string     `form:"q" binding:"required,min=1"`
	GroupID  *uuid.UUID `form:"group_id"`
	UserID   *uuid.UUID `form:"user_id"`
	FromDate *time.Time `form:"from_date"`
	ToDate   *time.Time `form:"to_date"`
	Limit    int        `form:"limit" binding:"omitempty,max=50"`
	Offset   int        `form:"offset" binding:"omitempty,min=0"`
}

// MessageSearchResult represents search results
type MessageSearchResult struct {
	Messages []MessageDTO `json:"messages"`
	Total    int          `json:"total"`
	Limit    int          `json:"limit"`
	Offset   int          `json:"offset"`
}

// Helper functions

// ToDTO converts a Message to MessageDTO
func (m *Message) ToDTO(sender *User) *MessageDTO {
	content := "" // Content would be decrypted by service layer

	dto := &MessageDTO{
		ID:          m.ID,
		SenderID:    m.SenderID,
		ReceiverID:  m.ReceiverID,
		GroupID:     m.GroupID,
		Content:     content,
		MessageType: m.MessageType,
		FileID:      m.FileID,
		IsEdited:    m.IsEdited,
		EditedAt:    m.EditedAt,
		ReadAt:      m.ReadAt,
		CreatedAt:   m.CreatedAt,
		UpdatedAt:   m.UpdatedAt,
	}

	if sender != nil {
		dto.Sender = sender.ToDTO()
	}

	return dto
}

// IsTextMessage checks if message is text
func (m *Message) IsTextMessage() bool {
	return m.MessageType == "text"
}

// IsFileMessage checks if message is a file
func (m *Message) IsFileMessage() bool {
	return m.MessageType == "file"
}

// IsMediaMessage checks if message is media
func (m *Message) IsMediaMessage() bool {
	return m.MessageType == "image" || m.MessageType == "video" || m.MessageType == "voice"
}

// IsRead checks if message has been read
func (m *Message) IsRead() bool {
	return m.ReadAt != nil
}

// CanEdit checks if message can be edited
func (m *Message) CanEdit(userID uuid.UUID) bool {
	// Can only edit own messages that are not deleted
	return m.SenderID == userID && !m.IsDeleted && m.CreatedAt.After(time.Now().Add(-15*time.Minute))
}

// CanDelete checks if message can be deleted
func (m *Message) CanDelete(userID uuid.UUID) bool {
	// Can only delete own messages
	return m.SenderID == userID && !m.IsDeleted
}
